### ISSUE TITLE
Toolbar button

### ISSUE THREAD

**Issue by mikhoul** [DanielKamkha/PlayPause#11]
Hi, 

I'd really like to have the choice of using the **"play" button** on the tab OR **on the toolbar**, it would be easier to reach the button if it was already at the same place on the toolbar than on "moving" tab :wink:

Also maybe in the future we could add support for skipping button and like/dislike button for some site that have those features.

Regards ! :musical_note:

**Comment by DanielKamkha** [comment]
I'm fine with creating a play/pause toolbar button and the options to have it either instead of or in addition to the current tab button. I'll add it in the next release or one after that.

As for the additional buttons, I definitely won't add them as tab buttons - that would be hijacking too much space from the tab text. Adding them as toolbar buttons is possible, though. No promises here, however, this will be a low-priority feature.

**Comment by mikhoul** [comment]
Thanks a lot ! :smile:

If I find some spare time after you had installed the Play/Pause button in the toolbar I will study the code and try to help you to implement the other buttons like Skip and like/dislike :loud_sound:

Regards !

**Comment by DanielKamkha** [comment]
Added in https://github.com/DanielKamkha/PlayPause/commit/06cf07a227b97f62b751ce95ecdf2b280df45f56
