### ISSUE TITLE
Integrate with Firefox mute control

### ISSUE THREAD

**Issue by nt1m** [DanielKamkha/PlayPause#23]
It would be nice if this could override the Firefox tab mute/unmute button on the relevant tabs.
It would allow this add-on: https://addons.mozilla.org/en-GB/firefox/addon/smart-tab-mute/ to work with this one. (eg. instead of muting/unmuting the tab, the tab would be paused/played)

**Comment by DanielKamkha** [comment]
The idea of overriding (or at least hiding) the built-in mute button is an interesting one. To think of it, one rarely needs to mute the tab while keeping it playing.

The compatibility with "Smart Tab Mute" is another thing. It could me more complicated than just overriding the mute button. I need to investigate this deeper.

**Comment by mikhoul** [comment]
@DanielKamkha  What would be better IMO would be to have the option to put in "pause" the audio/video in background tabs like the abandonned addon Be Quiet ---> https://github.com/sparhami/BeQuiet maybe some code could be reused ?   :octocat:

**Comment by DanielKamkha** [comment]
Auto-pausing background tabs would be an awesome feature. BeQuiet's code is rather old, I'd rather not spend time salvaging it. But will try to come up with some solution on my own.

**Comment by mikhoul** [comment]
@DanielKamkha    It could be easy to integrate it with Play/Pause, I looked quickly at the source of STM and it look feasible but I will look deeper to see if we can change the muting for the "pausing" of play/pause. At least the code of STM is very clear and simple not like the old BeQuiet ! :wink: 

In the next weeks/months I will look to add an option to have the play/pause button to the toolbar (fixed position) instead of tabs and maybe other optional buttons  like Up/Down vote and  skip song.  I really need those features for myself. :smirk_cat: 

I'm not really "good" at JS but I learn more everyday, maybe I will need some help ! :octocat:

**Comment by DanielKamkha** [comment]
STM is rather straightforward, I agree. It's a WebExtrension, while BeQuiet is an old-style XUL add-on.

@mikhoul And of course it would be cool if you could contribute.

**Comment by mikhoul** [comment]
> @mikhoul And of course it would be cool if you could contribute.

I will, I have few project to finish first but right after I will begin and use it at the same time to learn on Firefox addon API.  😊

**Comment by nt1m** [comment]
I think it may be possible to override https://dxr.mozilla.org/mozilla-central/source/browser/base/content/tabbrowser.xml#6749 with the add-on SDK. Overriding that (tab.toggleTabMute()) should integrate with all possible add-ons out there.

**Comment by DanielKamkha** [comment]
The plan is to implemented this as a part of the transition to WebExtensions API. Muted state could be handled there with tabs.onUpdated() and changeInfo.mutedInfo.

**Comment by DanielKamkha** [comment]
Play/Pause v2.0 (in repo, not published on AMO yet) uses WebExtensions API, which is incapable of responding to "click on tab title" event. Main functionality will thus be changed to respond to the "mute" button instead.
