### ISSUE TITLE
title don't change with addon enabled

### ISSUE THREAD

**Issue by CennoxX** [DanielKamkha/PlayPause#33]
If I have the add-on enabled in Firefox 54.0a2, the titles of tabs no longer change, where this was the case previously. The tooltips of respective tabs on the other hand show the current title and the window is also correctly named.
To understand open the debugger and write something like document.title = "newTitle".

**Comment by DanielKamkha** [comment]
Should've been fixed with https://github.com/DanielKamkha/PlayPauseFirefox/commit/91b8edf499142f3795a5233a6d5e3a0894d185d5. On AMO the fix is available since v1.2.5.

Please make sure your Play/Pause is update to the latest version. If the issue still persists afterwards, please say so. I'd also like to have an example, on which site(s) does this happen.

**Comment by CennoxX** [comment]
I am using v1.2.5 from 2017-03-13, if I open any website>F12>Console>document.title = "newTitle" nothing changes (with addon activated). This happens on (nearly?) every website, that has a dynamic title. For example http://time-in.info/timer.asp?minutes=1&start=y As said, the tooltips of respective tabs show the current title and the window is also correctly named.

**Comment by debiedowner** [comment]
I also have this issue; I think it started about a week ago when I updated to Firefox 53. Maybe it has to do with the changes in Firefox 53 about the display of tab titles, I don't know. ("The last few characters of shortened tab titles fade out instead of being replaced by ellipses to keep more of the title visible.") For example, on this website http://www.htmlbasix.com/titlebarmessage.shtml the title doesn't scroll after it finished loading when Play/Pause is enabled, even though the window title scrolls. Curiously, though, the problem doesn't persist if I move the tab right/left or into a new window; after I do that, updates are shown correctly on the tab title. Obviously I don't care about such gimmicks like scrolling title, but title change is also how I notice I have a new email without having to constantly check the contents of the tab, so I had to disable the add-on for the moment.

**Comment by Maartenwut** [comment]
I'm having this issue as well using version 1.2.8 and Firefox 53.0.3. A good example would be Gmail, where the title changes depending on the folder you are looking at.

**Comment by clockler** [comment]
Also having this issue - FF54 (though also on 53.0.3 - just updated to check) and extension 1.2.8. Only sites not affected by the extension's behaviour seem to be affected - `document.title = 'newTitle'` works fine on e.g. Bandcamp or YouTube, but does not work on Gmail. 

Other notes:
Reverting to 1.2.4 - pre-FF53 compatibility patch - appears to invert this behaviour: tab titles on Bandcamp are not alterable, but titles on other sites are.
Moving the tab even within the same window appears to "unlock" its title.

**Comment by DanielKamkha** [comment]
Play/Pause v2.0 (in repo, not published on AMO yet) uses WebExtensions API, which is incapable of responding to "click on tab title" event. Main functionality will thus be changed to respond to the "mute" button instead.
