### ISSUE TITLE
v2.0.0 Not on Firefox Addons Store

### ISSUE THREAD

**Issue by DavidCao22** [DanielKamkha/PlayPause#41]
Is there a timeline on getting v2.0.0 onto the Firefox Addons Store? Currently it's at 1.2.11

**Comment by DanielKamkha** [comment]
FF57 (the one that kills old-style extensions) is released to general public somewhere mid-November. The plan is to publish Play/Pause 2.x to AMO two weeks before that, to make the old version available for as long as possible.

The reason for this intentional delay is that transition to WebExtensions API kills one of the nicest features Play/Pause has: clickable play/pause indicator/button. It is simply not possible after FF57 hits the mass market.

Play/Pause itself is here to stay, but it would have to piggyback on "mute" button instead. So please enjoy the old style until November.

**Comment by DavidCao22** [comment]
@DanielKamkha What functionality will the extension have after FF57? If there is no clickability, is it now just reduced to being an indicator of which tabs have playing/paused media?

**Comment by DanielKamkha** [comment]
There is still a single clicky thing in the tab title: "mute" button. And that's the thing I'm going to hijack for the new version. So, the built-in "mute" button will perform the same function as the clickable indicator does now.

Moreover, the keyboard shortcut will be still available (though it will be Alt-Shift-P and not customizable, go say thanks to Mozilla for their awesome new APIs). A new addition will be a toolbar button with the same functionality as the shortcut (i.e. global "smart" play/pause).

You can try out the beta version for now if you are really curious:
https://addons.mozilla.org/firefox/downloads/latest-beta/play-pause/addon-625966-latest.xpi?src=dp-btn-devchannel
