### ISSUE TITLE
[Linux] Pause button is way bigger than the Play button.

### ISSUE THREAD

**Issue by Nildeala** [DanielKamkha/PlayPause#5]
Thanks for your awesome addon!

The Pause button is however quite big compared to the Play button. See my screenshots.

![capture du 2015-12-21 15-06-42](https://cloud.githubusercontent.com/assets/914451/11932272/86403846-a7f4-11e5-8ede-f04af9bc8d3a.png)
![capture du 2015-12-21 15-06-53](https://cloud.githubusercontent.com/assets/914451/11932273/8644c960-a7f4-11e5-8ca4-8710adab6b6d.png)

**Comment by fabienwang** [comment]
:+1: same issue over here (Firefox Nightly 46.0a1, Arch Linux)

**Comment by Transmigracion** [comment]
The same behavior on Debian 8.6

**Comment by Daerdemandt** [comment]
Same here:
![1487599577](https://cloud.githubusercontent.com/assets/814904/23128232/940b5098-f797-11e6-87fc-f53cee3a42ad.png)
![1487599606](https://cloud.githubusercontent.com/assets/814904/23128236/97f8ba56-f797-11e6-94d8-941ae186e487.png)
Firefox v50.0, ArchLinux.

I suppose one should also look [here](https://github.com/DanielKamkha/PlayPauseFirefox/blob/master/index.js#L15-L19) and attach screenshots of those symbols. Might be some fonts/unicode problem - I see playSymbolLarge as smaller than either playSymbol or plySymbolAlt (although discrepancy is not sa prominent as it is on tabs)

![1487599844](https://cloud.githubusercontent.com/assets/814904/23128347/0e628c9e-f798-11e6-9076-96369d56df8e.png)

**Comment by DanielKamkha** [comment]
This is a known issue, affecting Firefox on some versions of Linux. I have investigated it and successfully reproduced using a Ubuntu distro.

Since the play and pause symbols injected into the tab title a text characters (well, two characters for pause), they are affected by the font used in the tab title by Firefox itself. It affects Linux only, so FF must be using some specific fonts there.

I don't have a working solution for this yet. But if you know any HTML/CSS trick that would substitute a "good" font for the play/pause symbol, I might use this.

**Comment by Daerdemandt** [comment]
I've only had DevaJu fonts (ttf-dejavu package), installing more fonts (ttf-freefont) helped:

![1487700541](https://cloud.githubusercontent.com/assets/814904/23178098/9f097bdc-f882-11e6-9bc3-ed12354d0c4f.png)
![1487700573](https://cloud.githubusercontent.com/assets/814904/23178106/a220c3ac-f882-11e6-94f6-2bf1815768a9.png)

"Pause" is still bigger than "Play" but the difference is not as big.

However, additional fonts are no silver bullet:

![1487701769](https://cloud.githubusercontent.com/assets/814904/23178877/7429e21e-f885-11e6-8158-92286666a49b.png)
![1487701797](https://cloud.githubusercontent.com/assets/814904/23178879/76bc33ba-f885-11e6-93fd-d5300dc0a39f.png)

While the tab is active, the symbol is a part of tab's title, it's clikable and works fine (you can even see slight change in tab title's size to accomodate the difference between "play" and "pause" widths). However, if the tab is not active, the symbol invades other tab's title and is not clickable (since you'd niteract with *that* tab instead).

Without additional fonts, inactive pinned tab's width is calculated correctly.

![1487703382](https://cloud.githubusercontent.com/assets/814904/23180144/d5f6b09a-f889-11e6-8e6c-f4d52699ceac.png)

> if you know any HTML/CSS trick that would substitute a "good" font for the play/pause symbol, I might use this

I don't know what's allowed in tab titles. If you can only add text and style it then [this](https://developer.mozilla.org/en-US/docs/Web/CSS/::first-letter) is as close as it gets to styling a specific character (might work here!).

If you are allowed to add whole HTML tags then maybe just use [these](http://fontawesome.io/icons/#video-player) instead and bypass font inconsistencies altogether?

Or maybe try some other symbols, like these: ⏸ ⏯ .

**Comment by DanielKamkha** [comment]
I need to double-check, but if alternative fonts are allowed, then, yes, AwesomeFont would be a perfect solution.

**Comment by DanielKamkha** [comment]
Play/Pause v2.0 (in repo, not published on AMO yet) uses WebExtensions API, which is incapable of responding to "click on tab title" event. Main functionality will thus be changed to respond to the "mute" button instead.
